
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Course
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Course()
    {

        this.Enrollments = new HashSet<Enrollment>();

    }


    public int CourseID { get; set; }

    public string Title { get; set; }

    public Nullable<int> FacultyID { get; set; }

    public string Name { get; set; }

    public string Credits { get; set; }

    public Nullable<int> ClassID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Enrollment> Enrollments { get; set; }

    public virtual Faculty Faculty { get; set; }

    public virtual Class Class { get; set; }

}

}
