
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Faculty
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Faculty()
    {

        this.Courses = new HashSet<Course>();

    }


    public int FacultyID { get; set; }

    public string FacultyFirstName { get; set; }

    public string FacultyLastName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Course> Courses { get; set; }

}

}
