
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Student
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Student()
    {

        this.Enrollments = new HashSet<Enrollment>();

    }


    public int StudentID { get; set; }

    public Nullable<int> ClassID { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public Nullable<int> PhoneNo { get; set; }

    public string Email { get; set; }

    public Nullable<int> SectionID { get; set; }

    public int RollNo { get; set; }



    public virtual Class Class { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Enrollment> Enrollments { get; set; }

    public virtual Section Section { get; set; }

}

}
